language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

before_script:
  - npm install grunt-cli -g

script:
  - grunt test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker build -t isa-group/governify-registry .;
    docker build -t isa-group/governify-registry:$VERSION .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push isa-group/governify-registry;
    docker push isa-group/governify-registry:$VERSION;
    fi
