---
development:
  database:
    url: "mongodb://sas-devel.governify.io:27017/prosas"
  port: 8081
  logfile: "./logs/dev.log"
production:
  database:
    url: "mongodb://mongo/prosas"
  port: 8081
  logfile: "./logs/prod.log"
