---
development:
  database:
    url: "mongodb://dockers/governify-registry"
  port: 8080
  logfile: "./logs/dev.log"
production:
  database:
    url: "mongodb://sas-devel.governify.io:27017/prosas"
  port: 8080
  logfile: "./logs/prod.log"
