---
development:
  database:
    url: "mongodb://localhost:27017/prosas"
  port: 8081
  logfile: "./logs/dev.log"
  parallelProcess:
    guarantees: false
    metrics: false
  streaming: true
  statusBouncer: false
  maxAttempts: 10
  retryDelay: 2000
  email:
    defaultMailFrom: '"ISA-Group" <no-reply@isa.us.es>'
    messages:
      reloadAgreement:
        mailSubject: '[Governify] Su tarea ha finalizado'
        mailContent: "El cálculo de SLAs para el contrato <b>%s</b> ha sido actualizado en base a la información cargada en los logs. <p>Número actual de registros que se han tenido en cuenta para realizar los cálculos:</p>"

production:
  database:
    url: "mongodb://mongo/prosas"
  port: 8081
  logfile: "./logs/prod.log"
  parallelProcess:
    guarantees: false
    metrics: false
  streaming: true
  statusBouncer: false
  maxAttempts: 20
  retryDelay: 5000
  email:
    defaultMailFrom: '"ISA-Group" <no-reply@isa.us.es>'
    messages:
      reloadAgreement:
        mailSubject: '[Governify] Su tarea ha finalizado'
        mailContent: "El cálculo de SLAs para el contrato <b>%s</b> ha sido actualizado en base a la información cargada en los logs. <p>Estado actual de los logs:</p>"
