---
development:
  database:
    url: "mongodb://dockers:27017/prosas"
  port: 8081
  logfile: "./logs/dev.log"
  async:
    guarantees: false
    metrics: false
production:
  database:
    url: "mongodb://mongo/prosas"
  port: 8081
  logfile: "./logs/prod.log"
  async:
    guarantees: false
    metrics: false
