---
development:
  database:
    url: "mongodb://localhost/test"
  port: 8080
  logfile: "./logs/dev.log"
production:
  database:
    url: "ds025802.mlab.com:25802/governify-registry"
  port: 80
  logfile: "./logs/prod.log"
